### ISSUE TITLE
Roadmap – July

### ISSUE THREAD

**Issue by erlend-sh** [fishfolk/jumpy#2]
General features
- [x] Basic physics
- [x] Long-jump (slow descent)
- [x] Smart camera
- [x] Multiple maps
- [x] Score counter

Weapon behaviors

- [x] throwable sword
- [x] throwable grenade
- [x] mines
- [x] boxes (can kill with head-boink)
- [x] sproingers. Jump-boosters, that bounce you up even if you just run into them.
- [x] Shoes (for head-boinking)
