### ISSUE TITLE
Steam Deck: Tracking Issues / Improvements for Steam Deck 

### ISSUE THREAD

**Issue by MaxCWhitehead** [fishfolk/jumpy#920]
### Description

Instead of opening several issues I thought this might be helpful for list of things we may want to address for steam deck to better support it, for quality of life and "[Steam Deck Verified](https://www.steamdeck.com/en/verified)" badge

- [ ] Selecting text field (such as network matchmaking server setting) does not automatically open keyboard (requires Steam + X hotkey to open manually)
- [ ] Complete testing of graphics scaling fix for #904 with external display in game + desktop mode
- [ ] Add steam deck input badges natively when visualizing buttons (not a huge deal but on the list of requirements for "Steamdeck Verified" badge
- [ ] Test / Verify external gamepads work as expected for local multiplayer
- [ ] Review other steam deck verified requirements
